/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MYEXEC_H_RPCGEN
#define _MYEXEC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data_in {
	char command[1000];
	char argument[1000];
};
typedef struct data_in data_in;

struct data_out {
	char data_out[2048];
};
typedef struct data_out data_out;

#define PROG 0x31240000
#define MYEXEC 1

#if defined(__STDC__) || defined(__cplusplus)
#define MYEXEC 1
extern  data_out * myexec_1(data_in *, CLIENT *);
extern  data_out * myexec_1_svc(data_in *, struct svc_req *);
extern int prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MYEXEC 1
extern  data_out * myexec_1();
extern  data_out * myexec_1_svc();
extern int prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data_in (XDR *, data_in*);
extern  bool_t xdr_data_out (XDR *, data_out*);

#else /* K&R C */
extern bool_t xdr_data_in ();
extern bool_t xdr_data_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MYEXEC_H_RPCGEN */
