/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "myexec.h"
#include <string.h>

void prog_1(char *host, char command[100], char argument[1000])
{
	CLIENT *clnt;
	data_out *result_1;
	data_in myexec_1_arg;

#ifndef DEBUG
	clnt = clnt_create(host, PROG, MYEXEC, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	strcpy(myexec_1_arg.command, command);
	strcpy(myexec_1_arg.argument, argument);

	result_1 = myexec_1(&myexec_1_arg, clnt);
	if (result_1 == (data_out *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	else
	{
		printf("Result: \n%s\n", result_1->data_out);
	}

#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[])
{
	char *host;

	if (argc < 3)
	{
		printf("usage: %s server_host [-i] command [arguments]\n", argv[0]);
		exit(1);
	}
	host = argv[1];

	char command[100];
	char argument[100];
	strcpy(command, "");
	strcpy(argument, "");
	strcpy(command, argv[2]);
	/* wpisanie argumentow do tablicy */
	if (argc > 4)
	{
		if (argv[3][0] == '-') /* podano argumenty z minusem */
		{
			strcpy(argument, "-");
			for (int i = 3; i < argc; i++)
			{
				strcat(argument, argv[i] + 1);
			}
		}
		else /* podano argumenty bez minusow */
		{
			for (int i = 3; i < argc; i++)
			{
				if (i == 3)
				{
					strcat(argument, argv[i]);
				}
				else
				{
					strcat(argument, " ");
					strcat(argument, argv[i]);
				}
			}
		}
		prog_1(host, command, argument);
	}
	else
	{
		if (argc == 4)
		{
			if (strcmp(argv[2], "-i") == 0) /* jezeli podano tryb interaktywny */
			{
				strcpy(command, argv[3]);
				printf("Tryb interaktywny:\n");
				while (1)
				{
					char tmp[1000];
					strcpy(tmp, "");
					strcpy(argument, "");
					scanf("%[^\n]%*c", tmp);
					strcat(argument, "-i+ ");
					strcat(argument, tmp);
					prog_1(host, command, argument);
				}
			}
			else
			{
				strcpy(argument, "-");
				strcpy(argument, argv[3]);
				prog_1(host, command, argument);
			}
		}
		else
		{
			if (argc == 3)
			{
				strcpy(argument, "");
				prog_1(host, command, argument);
			}
		}
	}
	exit(0);
}
